### ISSUE TITLE
HU10  - Modulo Control Entrada-Salida

### ISSUE THREAD

**Issue by victor15210552** [victor15210552/FinishProyect#10]
### Descripción
Yo como usuario necesito un registro de las entradas y salidas de los niños para llevar un control dentro del club.

### Criterios de Aceptación

1.  Dado un Usuario que permita registrar la Entrada del Niño y del Staff mediante su codigo correspondiente.
2.  Dado un Usuario que permita registrar la Salida del Niño y del Staff mediante su codigo correspondiente.

###Lista de Tareas
- [ ] Crear interfaz.
- [ ] Crear Tabla de Registro E/S.
- [ ] Crear Validaciones de los campos.

**Comment by MaikHernandez** [comment]
Módulo completado.
